services:
  thermostat-api:
    build: ./
    privileged: true
    environment:
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
      - HOST=0.0.0.0
      - PORT=8000
      - STORAGE_PATH=/data/storage.db
      - DEFAULT_MODE=OFF
      - DEFAULT_TARGET_TEMPERATURE=20
      - PUBSUB_HOST=mosquitto
      - PUBSUB_PORT=1883
      - PUBSUB_CLIENT_ID=thermostat-api
      - PUBSUB_QOS=1
    ports:
      - "8000:8000"
    networks:
      - mqtt_network
      - monitoring_network
    volumes:
      - data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/_healthz"]
      interval: 15s
      timeout: 3s
      retries: 5
networks:
  mqtt_network:
    external: true
  monitoring_network:
    external: true
volumes:
  data:
    driver: local
